version: '3'

services:
  postgres-pgvector:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: postgres-pgvector
    environment:
      POSTGRES_DB: ppl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
